[colors.primary]
background = "#030303"
foreground = "#ffffff"

[colors.cursor]
text = "#030303"
cursor = "#ffffff"

[colors.vi_mode_cursor]
text = "#030303"
cursor = "#ffffff"

[colors.search.matches]
foreground = "#030303"
background = "#ffffff"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#aa8e99"
background = "#ffffff"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#030303"
red = "#847E83"
green = "#B0AAA3"
yellow = "#DFAAA6"
blue = "#EFD8A5"
magenta = "#AC97CC"
cyan = "#DAA7D7"
white = "#f3ccdb"

[colors.bright]
black = "#aa8e99"
red = "#b6b2b5"
green = "#dfddda"
yellow = "#faf2f1"
blue = "#fefefc"
magenta = "#e3dbee"
cyan = "#f8eff8"
white = "#ffffff"

[colors.dim]
black = "#ffffff"
red = "#b6b2b5"
green = "#dfddda"
yellow = "#faf2f1"
blue = "#fefefc"
magenta = "#e3dbee"
cyan = "#f8eff8"
white = "#aa8e99"
